version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: aitomato_postgres_db
    restart: always
    environment:
      POSTGRES_USER: aitomato_user
      POSTGRES_PASSWORD: aitomato_pw
      POSTGRES_DB: aitomato
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
